/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.sql.SQLException;
import dbconnect.koneksi;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author Yayan Sopyan ST
 */
public class transaction extends javax.swing.JFrame {

    private int Ltersedia,Htanah,Hbangunan,nDP,nPeriode;
    private String area,tipe;
    String SQL,no_pelanggan;
    int kode,randB;
    char randA;

    public transaction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNo_Pelanggan = new javax.swing.JTextField();
        txtNama_Pemesan = new javax.swing.JTextField();
        txtHargaTanah = new javax.swing.JTextField();
        cmb_area = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHargaBangunan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLuasTanah_Asli = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rb36 = new javax.swing.JRadioButton();
        rb45 = new javax.swing.JRadioButton();
        rb54 = new javax.swing.JRadioButton();
        txtLuasTanah_Tersedia = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        txtDP = new javax.swing.JTextField();
        txtPeriode = new javax.swing.JTextField();
        txtPPN = new javax.swing.JTextField();
        txtCicilan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cb_konfirmasi = new javax.swing.JCheckBox();
        btn_proses = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        imgLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transaksi");

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("No. Pelanggan");

        jLabel2.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Pemesan");

        jLabel3.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Area");

        jLabel4.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga Tanah/m2");

        txtNo_Pelanggan.setEditable(false);

        txtHargaTanah.setEditable(false);

        cmb_area.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        cmb_area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH --", "SYMPHONIA", "GIRILOKA", "CIPUTRA" }));
        cmb_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_areaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga Bangunan");

        jLabel6.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipe Rumah");

        txtHargaBangunan.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Luas Tanah Asli");

        txtLuasTanah_Asli.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Luas Tanah Tersedia");

        rb36.setBackground(new java.awt.Color(51, 51, 255));
        buttonGroup1.add(rb36);
        rb36.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        rb36.setForeground(new java.awt.Color(255, 255, 255));
        rb36.setText("Tipe-36");
        rb36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb36ActionPerformed(evt);
            }
        });

        rb45.setBackground(new java.awt.Color(51, 51, 255));
        buttonGroup1.add(rb45);
        rb45.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        rb45.setForeground(new java.awt.Color(255, 255, 255));
        rb45.setText("Tipe-45");
        rb45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb45ActionPerformed(evt);
            }
        });

        rb54.setBackground(new java.awt.Color(51, 51, 255));
        buttonGroup1.add(rb54);
        rb54.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        rb54.setForeground(new java.awt.Color(255, 255, 255));
        rb54.setText("Tipe-54");
        rb54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb54ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel9.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Harga");

        jLabel10.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DP");

        jLabel11.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Lama Cicilan");

        jLabel12.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PPN (10%)");

        jLabel13.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cicilan /bln");

        txtHarga.setEditable(false);

        txtPPN.setEditable(false);

        txtCicilan.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Bulan");

        cb_konfirmasi.setBackground(new java.awt.Color(102, 102, 255));
        cb_konfirmasi.setFont(new java.awt.Font("Fira Code SemiBold", 0, 16)); // NOI18N
        cb_konfirmasi.setForeground(new java.awt.Color(255, 255, 255));
        cb_konfirmasi.setText("Setuju");
        cb_konfirmasi.setEnabled(false);
        cb_konfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_konfirmasiActionPerformed(evt);
            }
        });

        btn_proses.setText("PROSES");
        btn_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prosesActionPerformed(evt);
            }
        });

        btn_simpan.setText("SIMPAN");
        btn_simpan.setEnabled(false);
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPPN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCicilan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(cb_konfirmasi))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_proses)
                        .addGap(60, 60, 60)
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_hapus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_konfirmasi))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_proses)
                    .addComponent(btn_simpan)
                    .addComponent(btn_hapus))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Fira Code SemiBold", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("MUHAMMAD RAMDHANI SOPYAN\n201011450557");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNama_Pemesan, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(txtNo_Pelanggan)
                            .addComponent(cmb_area, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtHargaTanah, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(imgLabel)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(rb36, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rb45, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rb54, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLuasTanah_Tersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(txtHargaBangunan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLuasTanah_Asli, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtNo_Pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(txtHargaBangunan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNama_Pemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHargaTanah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cmb_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtLuasTanah_Asli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rb36))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rb45)
                                    .addComponent(jLabel8))))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb54)
                            .addComponent(txtLuasTanah_Tersedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(imgLabel)))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem3.setText("Home");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setText("Tampil Data");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Cari Data");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new show().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new search().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new main().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void cmb_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_areaActionPerformed
        // TODO add your handling code here:
        if(cmb_area.getSelectedIndex() == 0){
            txtHargaTanah.setText("");
            txtHargaBangunan.setText("");
            imgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            imgLabel.setEnabled(false);
            area =null;
        } else if(cmb_area.getSelectedIndex() == 1){
            txtHargaTanah.setText("500000");
            txtHargaBangunan.setText("90000000");
            imgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("symphonia.png")));
            imgLabel.setEnabled(true);
            area = "SYMPHONIA";
        } else if(cmb_area.getSelectedIndex() == 2){
            txtHargaTanah.setText("600000");
            txtHargaBangunan.setText("120000000");
            imgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("giriloka.png")));
            imgLabel.setEnabled(true);
            area = "GIRILOKA";
        } else if(cmb_area.getSelectedIndex() == 3){
            txtHargaTanah.setText("700000");
            txtHargaBangunan.setText("150000000");
            imgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("ciputra.png")));
            imgLabel.setEnabled(true);
            area = "CIPUTRA";
        } 
    }//GEN-LAST:event_cmb_areaActionPerformed

    private void rb36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb36ActionPerformed
        // TODO add your handling code here:
        txtLuasTanah_Asli.setText("90");
        txtLuasTanah_Tersedia.setText("90");
        tipe = "Tipe-36";
    }//GEN-LAST:event_rb36ActionPerformed

    private void rb45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb45ActionPerformed
        // TODO add your handling code here:
        txtLuasTanah_Asli.setText("120");
        txtLuasTanah_Tersedia.setText("120");
        tipe = "Tipe-45";
    }//GEN-LAST:event_rb45ActionPerformed

    private void rb54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb54ActionPerformed
        // TODO add your handling code here:
        txtLuasTanah_Asli.setText("140");
        txtLuasTanah_Tersedia.setText("140");
        tipe = "Tipe-54";
    }//GEN-LAST:event_rb54ActionPerformed

    private void btn_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prosesActionPerformed
        // TODO add your handling code here:
        Checker();
        txtNo_Pelanggan.setText(""+no_pelanggan);
        cb_konfirmasi.setEnabled(true);
        Ltersedia = Integer.parseInt(txtLuasTanah_Asli.getText());
        Htanah = Integer.parseInt(txtHargaTanah.getText());
        Hbangunan = Integer.parseInt(txtHargaBangunan.getText());
        int tanah = Htanah * Ltersedia;
        int total = tanah + Hbangunan;
        txtHarga.setText("" + total);
        int nPpn = total/100*10;
        txtPPN.setText(""+nPpn);
        nDP = Integer.parseInt(txtDP.getText());
        int bayar = total + nPpn-nDP;
        nPeriode = Integer.parseInt(txtPeriode.getText());
        int nBulan = nPeriode;
        int nCicilan = bayar/nBulan;
        txtCicilan.setText(""+ nCicilan);
    }//GEN-LAST:event_btn_prosesActionPerformed

    private void cb_konfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_konfirmasiActionPerformed
        // TODO add your handling code here:
        if(cb_konfirmasi.isSelected()){
            JOptionPane.showMessageDialog(this, "Di Setujui Pelanggan ! ");
            btn_simpan.setEnabled(true);
        } else {
            btn_simpan.setEnabled(false);
        }
    }//GEN-LAST:event_cb_konfirmasiActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        try{
           Connection conn = koneksi.getConnection();
           PreparedStatement stmt = conn.prepareStatement("INSERT INTO "
           + "penjualan(nama, area, harga_tanah, harga_bangunan, "
           + "tipe_rumah, luas_tanah_a, luas_tanah_t, harga, dp, periode, ppn, cicilan, no_pelanggan)"
           + "values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
           
           stmt.setString(1, txtNama_Pemesan.getText());
           stmt.setString(2, area);
           stmt.setString(3, txtHargaTanah.getText());
           stmt.setString(4, txtHargaBangunan.getText());
           stmt.setString(5, tipe);
           stmt.setString(6, txtLuasTanah_Asli.getText());
           stmt.setString(7, txtLuasTanah_Tersedia.getText());
           stmt.setString(8, txtHarga.getText());
           stmt.setString(9, txtDP.getText());
           stmt.setString(10, txtPeriode.getText());
           stmt.setString(11, txtPPN.getText());
           stmt.setString(12, txtCicilan.getText());
           stmt.setString(13, no_pelanggan);

           stmt.executeUpdate();
           no_pelanggan = "";
           txtNo_Pelanggan.setText("");
           txtNama_Pemesan.setText("");
           cmb_area.setSelectedIndex(0);
           txtHargaTanah.setText("");
           txtHargaBangunan.setText("");
           rb36.setSelected(false);
           rb45.setSelected(false);
           rb54.setSelected(false);
           txtLuasTanah_Asli.setText("");
           txtLuasTanah_Tersedia.setText("");
           txtHarga.setText("");
           txtDP.setText("");
           txtPeriode.setText("");
           txtPPN.setText("");
           txtCicilan.setText("");
           cb_konfirmasi.setSelected(false);
           cb_konfirmasi.setEnabled(false);
           JOptionPane.showMessageDialog(this, "Berhasil ! ");
       } catch(SQLException e){
           JOptionPane.showMessageDialog(this, e);
           System.out.print(e);
       }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        no_pelanggan = "";
        txtNo_Pelanggan.setText("");
        txtNama_Pemesan.setText("");
        cmb_area.setSelectedIndex(0);
        txtHargaTanah.setText("");
        txtHargaBangunan.setText("");
        rb36.setSelected(false);
        rb45.setSelected(false);
        rb54.setSelected(false);
        txtLuasTanah_Asli.setText("");
        txtLuasTanah_Tersedia.setText("");
        txtHarga.setText("");
        txtDP.setText("");
        txtPeriode.setText("");
        txtPPN.setText("");
        txtCicilan.setText("");
        cb_konfirmasi.setSelected(false);
        cb_konfirmasi.setEnabled(false);
    }//GEN-LAST:event_btn_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_proses;
    private javax.swing.JButton btn_simpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cb_konfirmasi;
    private javax.swing.JComboBox<String> cmb_area;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton rb36;
    private javax.swing.JRadioButton rb45;
    private javax.swing.JRadioButton rb54;
    private javax.swing.JTextField txtCicilan;
    private javax.swing.JTextField txtDP;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtHargaBangunan;
    private javax.swing.JTextField txtHargaTanah;
    private javax.swing.JTextField txtLuasTanah_Asli;
    private javax.swing.JTextField txtLuasTanah_Tersedia;
    private javax.swing.JTextField txtNama_Pemesan;
    private javax.swing.JTextField txtNo_Pelanggan;
    private javax.swing.JTextField txtPPN;
    private javax.swing.JTextField txtPeriode;
    // End of variables declaration//GEN-END:variables

    private void Checker() {
        Random randNumb = new Random(); //objek random
            for (int i = 0; i < 5; i++) {
            randA = (char) (randNumb.nextInt(26) + 'A');
            System.out.print(randA);
            }
            for (int i = 0; i < 5; i++) {
            randB = randNumb.nextInt(100) + 1;
            System.out.print(randB);
            }
            no_pelanggan = "P_" + randA + "_"+randB;
    }
}
